### ISSUE TITLE
How do I run the example?

### ISSUE THREAD

**Issue by nicmcd** [sstsimulator/sst-external-element#2]
I followed the instructions here: http://sst-simulator.org/SSTPages/SSTBuildAndInstall10dot1dot0SeriesDetailedBuildInstructions/#sst-external-element

I installed only sst-core and sst-external-element. I can successfully run make. How do I run the example? 

I can run
```
$sst tests/simpleElementExample-test-001.py
```
which yields:
```
Invalid MIT-MAGIC-COOKIE-1 keyWARNING: Building component "simpleExternalElement" with no links assigned.
SimpleExternalElement-simpleExternalElement-> Config: maxRepeats=15, printFreq=5
SimpleExternalElement-simpleExternalElement-> Component is being setup.
SimpleExternalElement-simpleExternalElement-> Hello World!
SimpleExternalElement-simpleExternalElement-> Hello World!
SimpleExternalElement-simpleExternalElement-> Hello World!
SimpleExternalElement-simpleExternalElement-> Component is being finished.
Simulation is complete, simulated time: 150 ns
```

Since the documentation didn't state whether or not this is correct output, can you add this to the documentation and state what the intended output is?

**Comment by nmhamster** [comment]
@nicmcd - thanks for the feedback. If you get a "Simulation is complete" that means it met and appropriate valid exit condition. We can fix the documentation.

**Comment by nicmcd** [comment]
What is the intended behavior of tests/testsuite_default_sstexternalelement.py?

**Comment by gvoskuilen** [comment]
It's a test suite for the SST test infrastructure. You can run "sst-test-elements" to run the installed test suites (in this case, should be just the one).
