### ISSUE TITLE
Create multi-component example

### ISSUE THREAD

**Issue by nicmcd** [sstsimulator/sst-external-element#3]
[Feature request]

A primary feature of SST is the python specified component connections. It would be helpful if the example in this repository was slightly more complex to also show how python is used to connect components together. A simple example that is often used in other simulators is a token ring where a single token in passed around a ring. It seems like it would also be a useful example for exercising the MPI multiprocess parallelism.

What are you thoughts on whether this would be a useful example?

**Comment by gvoskuilen** [comment]
@nicmd Have you looked at simpleElementExample in sst-elements? It's intended to demonstrate SST usage/development. I think the intent of this repo was just to demonstrate creating element libraries outside of sst-elements.

That said, I like the idea of making this example a little more complex.

**Comment by nicmcd** [comment]
Thanks for the pointer. The example in sst-elements is very informative. Why is it located there? I'd suggest one location or the other, not both. Personally I'd chose in this repo, not sst-elements.
